version: '3'
services: 
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    container_name: 'database'
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./src/database/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "challengedatabase"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"